#!/usr/bin/env bash

_="
Sourced at every bash entry, by a source <me> statement added by create to bashrc.
Our Tasks:
- export an activation function with an acceptable name
- add us to known_bashenvs
- activate us if wanted.

We could be already activated -> then just source be_active via activate.d script
Else activate us if required or just export activation function
"


here="$(unset CDPATH && cd "$(dirname "$BASH_SOURCE")" && echo $PWD)"

add_activate_to_bashrc=false # we will activate us
require_ldd_weakref_fix=false # LD fix was detected necessary by create

parse_cli () {
    # those are set from the .bashrc statement from the installer:
    add_activate_to_bashrc=$1; shift
    require_ldd_weakref_fix=$1; shift
}

derive_conda_prefix_from_here() {
    conda_prefix="$(unset CDPATH && cd "$here/../../../../" && echo $PWD)"
}

if_active_then_source_be_active_and_return () {
    test "${CONDA_PREFIX:-}x" == "${conda_prefix}x" && {
        source "$conda_prefix/etc/conda/activate.d/bashenv.sh"
        return 0
    }
    return 1
}
make_us_known () {
    we_where_known=true # won't create activation function then
    known_bashenvs="${known_bashenvs:-}"
    [[ "$known_bashenvs" == *$conda_prefix* ]] && return 0
    export known_bashenvs="$known_bashenvs:$conda_prefix"
    we_where_known=false
}

get_ldd () {
    $require_ldd_weakref_fix || return 0
    echo "export LD_LIBRARY_PATH=\"$conda_prefix/lib:$LD_LIBRARY_PATH\""
}

export_activation_function_if_not_known () {
    $we_where_known && return 0
    # getting a function name which bash accepts:
    act_func_name="`python -sSc "if 1:
    import string
    c = string.digits + string.ascii_letters + '_'
    p, f = '$conda_prefix'.rsplit('/', 1)
    clean = lambda s: filter(lambda x: x in c, s)
    f, p = (clean(f), clean(p.replace('/', '_')))
    print('be_%s%s' % (f, p))
    " ` "
    local ldd="`get_ldd`"
    eval "$act_func_name () { $ldd; source \"$conda_prefix\"/bin/activate; }; export -f $act_func_name"
}

activate_us_if_wanted () {
    $add_activate_to_bashrc || return 0
    eval "`get_ldd`"
    source "$conda_prefix/bin/activate"
    if_active_then_source_be_active_and_return
}


main () {
    parse_cli $*
    derive_conda_prefix_from_here
    if_active_then_source_be_active_and_return && return 0 || true
    make_us_known
    export_activation_function_if_not_known
    activate_us_if_wanted
}

main $*
