#!/usr/bin/env bash

# File is sourced by /root/.bashrc after activation

set -u

#[[ $- == *i* ]] && be_interactive=true || be_interactive=false
[[ -t 1 ]] && be_interactive=true || be_interactive=false

$be_interactive && {
    # don't put duplicate lines or lines starting with space in the history.
    # See bash(1) for more options
    HISTCONTROL=ignoreboth

    # append to the history file, don't overwrite it
    shopt -s histappend

    # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
    HISTSIZE=1000
    HISTFILESIZE=2000

    # check the window size after each command and, if necessary,
    # update the values of LINES and COLUMNS.
    shopt -s checkwinsize
}

# evaluated in the `go` function (go bashe):
export be_go_target_bashenv="${be_dir:-}"
export be_interactive

